### ISSUE TITLE
Broken link on Averos homepage

### ISSUE THREAD

**Issue by rmorrise** [averos-io/averos-io-starter#8]
On the Averos homepage (wiforge.com), the big blue button at the bottom of the main banner that says "Averos Designer" doesn't work. I get a 404 error from this URL:

https://appbuilder.wiforge.com/averosdesigner

**Comment by houcemlaw** [comment]
Hello @rmorrise!

Thank you for opening this issue!
Obviously, since this is a link that is managed by angular router it won't be served by a static server.
Now all the traffic is directed to the Wibuild home page.
Please follow the link as described below so that you can access averosdesigner.

![designer](https://github.com/averos-io/averos-io-starter/assets/885141/19d13602-bb9e-4cb6-87b5-ecf3b7092210)
